"""
Django settings for streetwear_store project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from dotenv import load_dotenv
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pet&)nw881osi!2c^6_5#2&^38^&%*(q_8$q5=7^vxsf=wkq4u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://pilotshopkidwear-sn0w.onrender.com',
    'https://pilotshopkidwear.onrender.com',
    'https://novashop-production-b6eb.up.railway.app',
    'http://127.0.0.1',
    'http://127.0.0.1:8000',
    'http://localhost:8000/'
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_COOKIE_SECURE = False  # Must be False for HTTP/local dev; set True only in production HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'
CORS_ALLOWED_ORIGINS = [
    'https://pilotshopkidwear-sn0w.onrender.com',
    'https://pilotshopkidwear.onrender.com',
    'https://novashop-production-b6eb.up.railway.app',
    'http://localhost:8000/',
    'http://127.0.0.1:8000/',
]
CORS_ALLOWED_HEADERS = [
    'Content-Type',
    'Accept',
    'Origin',
    'Authorization',
    'Accept-Encoding',
    'DNT',
    'User-Agent',
    'If-Modified-Since',
    'Cache-Control',
    'Pragma',
    'If-None-Match',
]


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Local apps
    'products',
    'orders',
    'core',
    
    # django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for django-allauth
]
ROOT_URLCONF = 'streetwear_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.active_announcements',
                'products.context_processors.categories_processor',
                'orders.context_processors.cart_count_processor',
            ],
        },
    },
]

if not DEBUG:
    TEMPLATES[0]['APP_DIRS'] = False
    TEMPLATES[0]['OPTIONS']['loaders'] = [
        ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]),
    ]

WSGI_APPLICATION = 'streetwear_store.wsgi.application'

import dj_database_url
# Database
# https://docs.djangoproject.com/en/4.2/ref/ /#databases
import os
DATABASES = {
    'default': dj_database_url.parse(
        "postgresql://postgres:YwItQtTjmcnLQdkbWqIkdOKLqsjYTUhd@metro.proxy.rlwy.net:20576/railway",
        conn_max_age=600,
        ssl_require=True
    )
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise settings for production performance
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

WHITENOISE_MANIFEST_STRICT = False

# Media files (uploaded content)
# Media files (uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "pilotkidwear@gmail.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
CONTACT_US_EMAIL = os.getenv("CONTACT_US_EMAIL", "pilotkidwear@gmail.com")
DEFAULT_FROM_EMAIL = 'Pilot <pilotkidwear@gmail.com>'
ADMINS = [('Admin', 'admin@pilot.com')]

# Cart settings
COOKIE_CART_KEY = 'cart'

# Paymob Payment Gateway
PAYMOB_API_KEY         = os.getenv('PAYMOB_API_KEY', '')
PAYMOB_HMAC_SECRET     = os.getenv('PAYMOB_HMAC_SECRET', '')

# Wallet (Vodafone Cash, etc.)
PAYMOB_WALLET_INTEGRATION_ID = int(os.getenv('PAYMOB_WALLET_INTEGRATION_ID', '0') or '0')
PAYMOB_WALLET_IFRAME_ID       = os.getenv('PAYMOB_WALLET_IFRAME_ID', '')

# Credit / Debit Card
PAYMOB_CARD_INTEGRATION_ID   = int(os.getenv('PAYMOB_CARD_INTEGRATION_ID', '0') or '0')
PAYMOB_CARD_IFRAME_ID         = os.getenv('PAYMOB_CARD_IFRAME_ID', '')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin Admin Theme Settings
JAZZMIN_SETTINGS = {
    "site_title": "NOVA Admin",
    "site_header": "NOVA",
    "site_brand": "NOVA Administration",
    "site_logo": "images/IMG-20260408-WA0033.jpg",
    "login_logo": "images/IMG-20260408-WA0033.jpg",
    "site_logo_classes": "brand-image",
    "site_icon": "images/IMG-20260408-WA0033.jpg",
    "welcome_sign": "Welcome to NOVA Administration",
    "copyright": "NOVA Soft Underwear",
    "search_model": ["auth.User", "products.Product"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
        {"name": "Support", "url": "https://novasoftunderwear.com/support", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["sites", "socialaccount", "auth", "account"],
    "hide_models": [
        "orders.Cart", "orders.OrderTracking", 
        "products.ProductVariant", "products.Color", "products.Size", 
        "products.ProductReview", "products.Wishlist"
    ],
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-circle",
        "auth.Group": "fas fa-users-cog",
        "products.Product": "fas fa-shopping-bag",
        "products.Category": "fas fa-th-large",
        "products.ProductVariant": "fas fa-stream",
        "products.Color": "fas fa-palette",
        "products.Size": "fas fa-ruler-combined",
        "products.ProductReview": "fas fa-comment-alt",
        "products.Wishlist": "fas fa-heart",
        "products.Announcement": "fas fa-bullhorn",
        "orders.Order": "fas fa-receipt",
        "orders.Cart": "fas fa-shopping-cart",
        "orders.Offer": "fas fa-percentage",
        "orders.ShippingMethod": "fas fa-truck-loading",
        "orders.OrderTracking": "fas fa-route",
    },
    "order_with_respect_to": ["orders", "products", "auth"],
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "custom_css": "css/admin.css",
    "dashboard_side_widgets": [
        {
            "title": "Quick Actions",
            "template": "admin/widgets/quick_actions.html",
        },
        {
            "title": "Advanced Management",
            "template": "admin/widgets/advanced_management.html",
        }
    ],
}

JAZZMIN_UI_CONFIG = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_fixed": True,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-indigo",
        "secondary": "btn-outline-indigo",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Django-allauth settings
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth configuration
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Change to 'mandatory' for production
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = False
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_USERNAME = True
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"

# Social account settings
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_QUERY_EMAIL = True

# Redirect URLs
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# Google OAuth2 settings (will be configured in admin or environment variables)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_OAUTH_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_OAUTH_SECRET', ''),
            'key': '',
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}
