"""
Django settings for streetwear_store project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from dotenv import load_dotenv
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pet&)nw881osi!2c^6_5#2&^38^&%*(q_8$q5=7^vxsf=wkq4u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['pilotshopkidwear-sn0w.onrender.com','pilotshopkidwear.onrender.com','127.0.0.1','127.0.0.1:8000','localhost','localhost:8000']

CSRF_TRUSTED_ORIGINS = [
    'https://pilotshopkidwear-sn0w.onrender.com',
    'https://pilotshopkidwear.onrender.com',
    'http://127.0.0.1',
    'http://127.0.0.1:8000',
    'http://localhost:8000/'
]
CSRF_COOKIE_SECURE = False  # Must be False for HTTP/local dev; set True only in production HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'
CORS_ALLOWED_ORIGINS = [
    'https://pilotshopkidwear-sn0w.onrender.com',
    'https://pilotshopkidwear.onrender.com',
    'http://localhost:8000/',
    'http://127.0.0.1:8000/',
]
CORS_ALLOWED_HEADERS = [
    'Content-Type',
    'Accept',
    'Origin',
    'Authorization',
    'Accept-Encoding',
    'DNT',
    'User-Agent',
    'If-Modified-Since',
    'Cache-Control',
    'Pragma',
    'If-None-Match',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Local apps
    'products',
    'orders',
    'core',
    
    # Whitenoise
    'whitenoise.runserver_nostatic',
    
    # django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Add this line for language selection
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for django-allauth
]
ROOT_URLCONF = 'streetwear_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'streetwear_store.wsgi.application'

import dj_database_url
# Database
# https://docs.djangoproject.com/en/4.2/ref/ /#databases
import os
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
# DATABASES['default'] = dj_database_url.parse("postgresql://root:BeQEZ02zRla90gLSgFkz2tZSACtFcFKe@dpg-d3o0bf24d50c73a07o90-a.oregon-postgres.render.com/pilotkidwear")
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True

# django-allauth settings
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth configuration
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'optional'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


USE_TZ = True

# Available languages
from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ('en', _('English')),
]

# Locale paths
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploaded content)
# Media files (uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = "pilotkidwear@gmail.com"
EMAIL_HOST_PASSWORD = "mrtysklhzrqmuxmm"
CONTACT_US_EMAIL = "pilotkidwear@gmail.com"
DEFAULT_FROM_EMAIL = 'Pilot <pilotkidwear@gmail.com>'
ADMINS = [('Admin', 'admin@pilot.com')]

# Cart settings
COOKIE_CART_KEY = 'cart'

# Paymob Payment Gateway
PAYMOB_API_KEY         = os.getenv('PAYMOB_API_KEY', '')
PAYMOB_HMAC_SECRET     = os.getenv('PAYMOB_HMAC_SECRET', '')

# Wallet (Vodafone Cash, etc.)
PAYMOB_WALLET_INTEGRATION_ID = int(os.getenv('PAYMOB_WALLET_INTEGRATION_ID', '0') or '0')
PAYMOB_WALLET_IFRAME_ID       = os.getenv('PAYMOB_WALLET_IFRAME_ID', '')

# Credit / Debit Card
PAYMOB_CARD_INTEGRATION_ID   = int(os.getenv('PAYMOB_CARD_INTEGRATION_ID', '0') or '0')
PAYMOB_CARD_IFRAME_ID         = os.getenv('PAYMOB_CARD_IFRAME_ID', '')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django-allauth settings
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth configuration
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Change to 'mandatory' for production
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = False
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_USERNAME = True
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"

# Social account settings
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_QUERY_EMAIL = True

# Redirect URLs
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# Google OAuth2 settings (will be configured in admin or environment variables)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '586097926838-ecvdhgt06bvppole80n6ulrok965jeb3.apps.googleusercontent.com',
            'secret': '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',
            'key': '',
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
