# Generated by Django 4.2.7 on 2026-04-15 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_offer_cart_offer_order_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('bogo', 'Buy 1 Get 1 Free'), ('b1g2', 'Buy 1 Get 2 Free')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
