# Generated by Django 4.2.7 on 2026-04-09 17:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Main announcement message shown to customers')),
                ('announcement_type', models.CharField(choices=[('info', 'Info'), ('discount', 'Discount / Sale'), ('new_arrival', 'New Arrival'), ('event', 'Event')], default='info', max_length=20)),
                ('has_discount', models.BooleanField(default=False)),
                ('discount_code', models.CharField(blank=True, help_text='Promo / coupon code to display', max_length=50)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='Discount percentage (e.g. 20 for 20% off)', null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank to show indefinitely', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
