# Generated by Django 4.2.7 on 2026-04-12 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set a lower price for sales (e.g., from 200 to 170)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
